function createfigure1(X1, Y1)
%CREATEFIGURE1(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 28-Oct-2018 10:43:31

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','Sistema no lineal','LineWidth',1.5,...
    'Color',[1 0 0]);

% Create xlabel
xlabel({'tiempo(segundos)'});

% Create title
title({'Biomasa de la población, x0'});

% Create ylabel
ylabel({'x(t)'});

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 400]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[2 2.9]);
% Set the remaining axes properties
set(axes1,'FontName','Caladea','FontSize',16);
