function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 26-Oct-2018 08:55:36

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',1.5);
set(plot1(1),'DisplayName','Sistema no lineal','Color',[1 0 0]);
set(plot1(2),'DisplayName','Sistema lineal','Color',[0 0 1]);

% Create ylabel
ylabel('x(t)');

% Create xlabel
xlabel('t(segundos)');

% Create title
title({'Biomasa de la población.'});

% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[2.8 3]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Cambria','FontSize',16);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.697844045327795 0.607569694134162 0.184159569441118 0.0723833917893376]);

