function figure2(X1, YMatrix1, YMatrix2, YMatrix3)
%CREATEFIGURE(X1, YMatrix1, YMatrix2, YMatrix3)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data
%  YMATRIX3:  matrix of y data

%  Auto-generated by MATLAB on 18-Aug-2018 17:18:59

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.1296875 0.733568075117371 0.286979166666667 0.234741784037559]);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'LineWidth',1.5);
set(plot1(2),'Color',[0 0 0]);

% Create ylabel
ylabel('X(t)','FontName','Cambria');

% Create xlabel
xlabel('Tiempo(s)','FontName','Cambria');

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Cambria','FontSize',14);
% Create axes
axes2 = axes('Parent',figure1,...
    'Position',[0.130208333333333 0.410798122065728 0.286979166666667 0.234741784037559]);
hold(axes2,'on');

% Create multiple lines using matrix input to plot
plot2 = plot(X1,YMatrix2,'Parent',axes2,'LineWidth',1.5);
set(plot2(1),'Color',[1 0 0]);
set(plot2(2),'Color',[0 0 0]);

% Create ylabel
ylabel('CE(t)','FontName','Cambria');

% Create xlabel
xlabel('Tiempo(s)','FontName','Cambria');

box(axes2,'on');
% Set the remaining axes properties
set(axes2,'FontName','Cambria','FontSize',14);
% Create axes
axes3 = axes('Parent',figure1,...
    'Position',[0.129166666666667 0.0868544600938967 0.288541666666667 0.237089201877934]);
hold(axes3,'on');

% Create multiple lines using matrix input to plot
plot3 = plot(X1,YMatrix3,'Parent',axes3,'LineWidth',1.5);
set(plot3(1),'Color',[1 0.843137264251709 0]);
set(plot3(2),'Color',[0 0 0]);

% Create ylabel
ylabel({'C(t)',''},'FontName','Cambria');

% Create xlabel
xlabel('Tiempo(s)','FontName','Cambria');

box(axes3,'on');
% Set the remaining axes properties
set(axes3,'FontName','Cambria','FontSize',14);
