function figura(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 18-Aug-2018 15:21:50

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.13 0.116591928251121 0.393958333333333 0.829596412556056]);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',1.5,'Parent',axes1);
set(plot1(1),'DisplayName','X(t)');
set(plot1(2),'DisplayName','Ce(t)');
set(plot1(3),'DisplayName','C(t)');

% Create ylabel
ylabel('Variables de estado');

% Create xlabel
xlabel('Tiempo (s)');

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Cambria','FontSize',15);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.458810763280425 0.701669155060503 0.0587239589417974 0.130418538013738]);

