function figura2(X1, Y1, Y2, Y3)
%CREATEFIGURE(X1, Y1, Y2, Y3)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Y2:  vector of y data
%  Y3:  vector of y data

%  Auto-generated by MATLAB on 18-Aug-2018 16:09:11

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(3,1,1,'Parent',figure1);
hold(subplot1,'on');

% Create plot
plot(X1,Y1,'Parent',subplot1,'LineWidth',1.5);

% Create ylabel
ylabel('X(t)');

% Create xlabel
xlabel('Tiempo(s)');

box(subplot1,'on');
% Set the remaining axes properties
set(subplot1,'FontName','Cambria','FontSize',14);
% Create subplot
subplot2 = subplot(3,1,2,'Parent',figure1);
hold(subplot2,'on');

% Create plot
plot(X1,Y2,'Parent',subplot2,'LineWidth',1.5,'Color',[1 0 0]);

% Create ylabel
ylabel('CE(t)');

% Create xlabel
xlabel('Tiempo(s)');

box(subplot2,'on');
% Set the remaining axes properties
set(subplot2,'FontName','Cambria','FontSize',14);
% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.13 0.137834568246812 0.775 0.187900725870835]);
hold(axes1,'on');

% Create plot
plot(X1,Y3,'Parent',axes1,'LineWidth',1.5,'Color',[1 0.843137264251709 0]);

% Create ylabel
ylabel({'C(t)',''});

% Create xlabel
xlabel('Tiempo(s)');

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Cambria','FontSize',14);
