function grafnum(X1, Y1, X2, Y2, X3, Y3, Y4, Y5, Y6, Y7, Y8, Y9)
%CREATEFIGURE(X1, Y1, X2, Y2, X3, Y3, Y4, Y5, Y6, Y7, Y8, Y9)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data
%  Y4:  vector of y data
%  Y5:  vector of y data
%  Y6:  vector of y data
%  Y7:  vector of y data
%  Y8:  vector of y data
%  Y9:  vector of y data

%  Auto-generated by MATLAB on 18-Aug-2018 23:14:59

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.410797101449275 0.120739445745763 0.213405797101449 0.804260554254237]);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'Parent',axes1,'DisplayName','Euler','LineWidth',1);

% Create plot
plot(X2,Y2,'Parent',axes1,'DisplayName','Runge Kutta','LineWidth',1);

% Create plot
plot(X3,Y3,'Parent',axes1,'DisplayName','Simulink','LineWidth',1);

% Create ylabel
ylabel('CE(t)');

% Create xlabel
xlabel('Tiempo(s)');

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Cambria','FontSize',14);
% Create legend
legend(axes1,'show');

% Create subplot
subplot1 = subplot(1,3,3,'Parent',figure1);
hold(subplot1,'on');

% Create plot
plot(X1,Y4,'Parent',subplot1,'DisplayName','Euler','LineWidth',1);

% Create plot
plot(X2,Y5,'Parent',subplot1,'DisplayName','Runge Kutta','LineWidth',1);

% Create plot
plot(X3,Y6,'Parent',subplot1,'DisplayName','Simulink','LineWidth',1);

% Create ylabel
ylabel('C(t)');

% Create xlabel
xlabel('Tiempo(s)');

box(subplot1,'on');
% Set the remaining axes properties
set(subplot1,'FontName','Cambria','FontSize',14);
% Create legend
legend1 = legend(subplot1,'show');
set(legend1,...
    'Position',[0.803862846297109 0.27715193250839 0.0910156263783573 0.140814561157954]);

% Create axes
axes2 = axes('Parent',figure1,...
    'Position',[0.13 0.120739459440517 0.213405797101449 0.804260540559483]);
hold(axes2,'on');

% Create plot
plot(X1,Y7,'DisplayName','Euler','LineWidth',1);

% Create plot
plot(X2,Y8,'Parent',axes2,'DisplayName','Runge Kutta','LineWidth',1);

% Create plot
plot(X3,Y9,'DisplayName','Simulink','LineWidth',1);

% Create ylabel
ylabel('X(t)');

% Create xlabel
xlabel('Tiempo(s)');

box(axes2,'on');
% Set the remaining axes properties
set(axes2,'FontName','Cambria','FontSize',14);
% Create legend
legend2 = legend(axes2,'show');
set(legend2,...
    'Position',[0.241623262883061 0.179231654902127 0.0910156263783575 0.140814561157954]);

